version: 2.1
orbs:
  orbs: circleci/orb-tools@8.3.0
jobs:
  verify:
    docker:
      - image: circleci/openjdk
    steps:
      - checkout
      - jabba/setup:
          when: always
      - jabba/install:
          version: openjdk@1.9
          when: always
      - jabba/install:
          version: openjdk@1.9
          when: always
      - jabba/use:
          version: openjdk@1.9
          when: always
      - run:
          command: |
            java -version 2>&1 | grep -i openjdk
            java -version 2>&1 | grep -i 'build 9'
      - jabba/use:
          version: openjdk@1.10
          when: always
      - run:
          command: |
            java -version 2>&1 | grep -i openjdk
            java -version 2>&1 | grep -i 'build 10'
      - run: ls .jabba

workflows:
  default:
    jobs:
      - verify:
          filters:
            tags:
              only: /.*/
      - orbs/publish:
          orb-path: .circleci/orbs/jabba.yml
          orb-ref: ayte/jabba@$CIRCLE_TAG
          publish-token-variable: CIRCLECI_TOKEN
          requires:
            - verify
          context: circleci.com
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /\d+\.\d+\.\d+/

